### ISSUE TITLE
Failed to initialize when hvac mode is "off"

### ISSUE THREAD

**Issue by Maczuga** [andersonshatch/midea-ac-py#1]
You can turn the AC off from UI, but if you reset your HA during that - it fails to initialize. After that it won't init, even with AC on - due to status being retrieved from old state instead from the server.
My guess is that "off" mode is missing here:
https://github.com/andersonshatch/midea-ac-lib/blob/91b6dc46778f60ee8d681c820881685fc0ecc8de/midea/device.py#L85

Note: I did not alter the AC state using remote or app - only using Lovelace UI card.

Stack trace:
> Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 226, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 249, in _async_write_ha_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 155, in state
    return self.hvac_mode
  File "/config/custom_components/midea/climate.py", line 207, in hvac_mode
    self._device.operational_mode = ac.operational_mode_enum[self._old_state.state]
  File "/usr/local/lib/python3.7/enum.py", line 352, in __getitem__
    return cls._member_map_[name]
KeyError: 'off'

**Comment by msanchezt** [comment]
I think you are right, but it's not just about adding "off" state, but "HVAC_MODE_OFF", [as defined on official documentation](https://developers.home-assistant.io/blog/2019/07/03/climate-cleanup.html) about changes on Climate component.

Specifically, I'm referring to this phrase:

> The is_on property has been removed. If a device is able to turn off, it should include the hvac mode HVAC_MODE_OFF.

I believe we can similar fix as was done for Sensibo component regarding HVAC_MODE_OFF:

https://github.com/home-assistant/home-assistant/pull/25016/files/b7b1e87071d15955b4abd36d6f63384d2ef922e4

**Comment by Maczuga** [comment]
I can confirm, that https://github.com/andersonshatch/midea-ac-py/commit/f5e75b281365311c38f3abfa31e5d743ed169cc8 fixes the issue
