### ISSUE TITLE
Setup of platform midea is taking over 10 seconds.

### ISSUE THREAD

**Issue by Cireasa23** [andersonshatch/midea-ac-py#16]
2019-11-21 01:25:14 WARNING (MainThread) [homeassistant.components.climate] Setup of platform midea is taking over 10 seconds.

Update of climate.midea_175364564 is taking over 10 seconds

Hello,

I am bothering you with a little problem, I have a lot of warnings with taking over 10 seconds 
I have 3 devices
for each device I have this problem.
This is the fifth time I have installed Midea custom component and the last time is done from HACS.

I am using HASS.io Rasp 3B+

arch | armv7l
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.4
version | 0.101.3
virtualenv | false

2019-11-21 01:40:16 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.midea_17592186088169 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 270, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 448, in async_device_update
    await self.async_update()
  File "/config/custom_components/midea/climate.py", line 111, in async_update
    await self.hass.async_add_executor_job(self._device.refresh)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/midea/device.py", line 146, in refresh
    data = self._cloud_service.appliance_transparent_send(self.id, data)
  File "/usr/local/lib/python3.7/site-packages/midea/cloud.py", line 173, in appliance_transparent_send
    'applianceId': id
  File "/usr/local/lib/python3.7/site-packages/midea/cloud.py", line 93, in api_request
    return self.api_request(endpoint, args)
  File "/usr/local/lib/python3.7/site-packages/midea/cloud.py", line 93, in api_request
    return self.api_request(endpoint, args)
  File "/usr/local/lib/python3.7/site-packages/midea/cloud.py", line 93, in api_request
    return self.api_request(endpoint, args)
  File "/usr/local/lib/python3.7/site-packages/midea/cloud.py", line 95, in api_request
    raise RecursionError()
RecursionError
2019-11-21 01:53:57 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.midea_17592186088172 is taking over 10 seconds
2019-11-21 01:54:21 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.midea_17592186088172 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 270, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 448, in async_device_update
    await self.async_update()
  File "/config/custom_components/midea/climate.py", line 111, in async_update
    await self.hass.async_add_executor_job(self._device.refresh)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/midea/device.py", line 146, in refresh
    data = self._cloud_service.appliance_transparent_send(self.id, data)
  File "/usr/local/lib/python3.7/site-packages/midea/cloud.py", line 173, in appliance_transparent_send
    'applianceId': id
  File "/usr/local/lib/python3.7/site-packages/midea/cloud.py", line 93, in api_request
    return self.api_request(endpoint, args)
  File "/usr/local/lib/python3.7/site-packages/midea/cloud.py", line 93, in api_request
    return self.api_request(endpoint, args)
  File "/usr/local/lib/python3.7/site-packages/midea/cloud.py", line 95, in api_request
    raise RecursionError()
RecursionError

Thank you for your time!
Best regards,
Catalin

**Comment by Cireasa23** [comment]
Any ideas ?

[home-assistant.log](https://github.com/andersonshatch/midea-ac-py/files/3879865/home-assistant.log)

**Comment by velaar** [comment]
For the 10s limit, it is probably just one of the performance limitations of running HASS on RPI. As the API is relatively slow and highly depends on the speed and delays in your internet connection . Updating multiple devices might push the time over the 10s expectation of HASS. However the recursion exception should be addressed at some point.

**Comment by Cireasa23** [comment]
Thank you !
