### ISSUE TITLE
RecursionError since upgrade  to 107.7

### ISSUE THREAD

**Issue by Dinges28** [andersonshatch/midea-ac-py#20]
After months of working without any problems, since updating to 0.107.7 form 107.5 i get the following error.

`[homeassistant.helpers.entity] Update for climate.airco fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 474, in async_device_update
    await self.async_update()
  File "/home/homeassistant/.homeassistant/custom_components/midea/climate.py", line 111, in async_update
    await self.hass.async_add_executor_job(self._device.refresh)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/midea/device.py", line 146, in refresh
    data = self._cloud_service.appliance_transparent_send(self.id, data)
  File "/srv/homeassistant/lib/python3.7/site-packages/midea/cloud.py", line 173, in appliance_transparent_send
    'applianceId': id
  File "/srv/homeassistant/lib/python3.7/site-packages/midea/cloud.py", line 93, in api_request
    return self.api_request(endpoint, args)
  File "/srv/homeassistant/lib/python3.7/site-packages/midea/cloud.py", line 95, in api_request
    raise RecursionError()
RecursionError
`

**Comment by andersonshatch** [comment]
Is your device still available in the mobile app?
Version upgrade should not have made any difference to this component, especially just patch upgrade. Hopefully some transient condition.

**Comment by Dinges28** [comment]
The device is still visible and also controllable in the app. although...... if I do a test (... -> check device) it comes with an error 4042.

**Comment by Dinges28** [comment]
I removed the AC from the app, removed it from home assistant entities, added again to App, restarted Home Assistant.

it works again!!!
