### ISSUE TITLE
Recursion error

### ISSUE THREAD

**Issue by fritsjuuh** [andersonshatch/midea-ac-py#23]
Hi,

I can't seem to get the plugin to work with HASS. In the log it shows:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    await self.async_update()
  File "/config/custom_components/midea/climate.py", line 111, in async_update
    await self.hass.async_add_executor_job(self._device.refresh)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/midea/device.py", line 146, in refresh
    data = self._cloud_service.appliance_transparent_send(self.id, data)
  File "/usr/local/lib/python3.7/site-packages/midea/cloud.py", line 173, in appliance_transparent_send
    'applianceId': id
  File "/usr/local/lib/python3.7/site-packages/midea/cloud.py", line 95, in api_request
    raise RecursionError()
RecursionError

It does show my 4 devices so the login credentials seem to work.

Please advise.

**Comment by msanchezt** [comment]
Same issue here, I was about to post the same.

It was working on the past with the same "RecursionError" here and there, but now it's all the time over the logs:

`2020-04-21 15:53:11 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.midea_17592186093801 is taking over 10 seconds
2020-04-21 15:53:11 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.midea_17592186093810 is taking over 10 seconds
2020-04-21 15:53:11 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.midea_17592186093801 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    await self.async_update()
  File "/config/custom_components/midea/climate.py", line 111, in async_update
    await self.hass.async_add_executor_job(self._device.refresh)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/midea/device.py", line 146, in refresh
    data = self._cloud_service.appliance_transparent_send(self.id, data)
  File "/usr/local/lib/python3.7/site-packages/midea/cloud.py", line 173, in appliance_transparent_send
    'applianceId': id
  File "/usr/local/lib/python3.7/site-packages/midea/cloud.py", line 95, in api_request
    raise RecursionError()
RecursionError
2020-04-21 15:53:21 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.midea_17592186093810 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    await self.async_update()
  File "/config/custom_components/midea/climate.py", line 111, in async_update
    await self.hass.async_add_executor_job(self._device.refresh)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/midea/device.py", line 146, in refresh
    data = self._cloud_service.appliance_transparent_send(self.id, data)
  File "/usr/local/lib/python3.7/site-packages/midea/cloud.py", line 173, in appliance_transparent_send
    'applianceId': id
  File "/usr/local/lib/python3.7/site-packages/midea/cloud.py", line 95, in api_request
    raise RecursionError()
RecursionError`

Can anyone suggest a way to do some troubleshothing or enable some debugging, maybe?

**Comment by msanchezt** [comment]
Some more insight on what is happening on my end:

- I'm able to turn on/off/set any value from Home Assistant to the Midea device.
- Home Assistant is not able to show the current status of the Midea device if it's set throug the app or the thermostat.

I believe the following error is only-related with Home Assistant trying to get the state of the device, but not related to setting the state (which seems to be working fine).

**Comment by stoprocent** [comment]
+1

**Comment by fritsjuuh** [comment]
On my end I'm unable to do anything with the integration, I can't turn the AC's on or off.
It is detecting the AC's in my account though, I'm just unable to control them.

**Comment by msanchezt** [comment]
Adding some more info in case this helps. Beginning with version 0.109 I see this loop error:

`2020-05-03 18:14:12 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for midea doing I/O at custom_components/midea/climate.py, line 57: devices = client.devices()`
