### ISSUE TITLE
Single request tend to fail after some inactivity 

### ISSUE THREAD

**Issue by Maczuga** [andersonshatch/midea-ac-py#3]
After not issuing any commands for some hours - next command fails (throwing error below). After that error all following commands are working as intended. I think I remember that error occurred on parent repository. 

Action I tried to perform was setting hvac mode to 'dry'. 

Stack trace:
> Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 121, in handle_call_service
    connection.context(msg))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1150, in async_call
    self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1172, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 194, in handle_service
    required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 316, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 337, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/config/custom_components/midea/climate.py", line 276, in async_set_hvac_mode
    await self.apply_changes()
  File "/config/custom_components/midea/climate.py", line 95, in apply_changes
    await self.hass.async_add_executor_job(self._device.apply)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/midea/device.py", line 165, in apply
    data = self._cloud_service.appliance_transparent_send(self.id, data)
  File "/usr/local/lib/python3.7/site-packages/midea/cloud.py", line 174, in appliance_transparent_send
    'applianceId': id
  File "/usr/local/lib/python3.7/site-packages/midea/cloud.py", line 92, in api_request
    return self.api_request(endpoint, args)
  File "/usr/local/lib/python3.7/site-packages/midea/cloud.py", line 94, in api_request
    raise RecursionError()
RecursionError

**Comment by Maczuga** [comment]
It seems that 3 concurrent API request failed throwing following error. However from what I have noticed - next execution always work. 
Perhaps there should be a timeout between api call retries (1sec or configurable)? Configurable retry count would be also nice.
