### ISSUE TITLE
Integration looses connection and only HA restart gets it to work again

### ISSUE THREAD

**Issue by dprauser** [andersonshatch/midea-ac-py#31]
**Describe the bug**
Aftee a few hours of being connected, the i tegration looses its connection to the Midea Cloud and no further control is possible. A HA restart and fresh connection fixes the communication and control works again for a few hours.

**To Reproduce**
1. Use Integarteion with HA 111.2
2. Control Midea AC as you would do normally
3. Wait a few hours
4. Try to turn off AC with HA App or Webinterface

**Screenshots / Logs**
Logger: homeassistant.helpers.entity
Source: custom_components/midea/climate.py:115
First occurred: 2:45:13 (4 occurrences)
Last logged: 8:48:08
Update for climate.midea_20890720942101 failsTraceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state await self.async_device_update() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update await self.async_update() File "/config/custom_components/midea/climate.py", line 115, in async_update await self.hass.async_add_executor_job(self._device.refresh) File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/usr/local/lib/python3.7/site-packages/midea/device.py", line 146, in refresh data = self._cloud_service.appliance_transparent_send(self.id, data) File "/usr/local/lib/python3.7/site-packages/midea/cloud.py", line 173, in appliance_transparent_send 'applianceId': id File "/usr/local/lib/python3.7/site-packages/midea/cloud.py", line 93, in api_request return self.api_request(endpoint, args) File "/usr/local/lib/python3.7/site-packages/midea/cloud.py", line 95, in api_request raise RecursionError() RecursionError

**Versions**
 - Home Assistant version: 111.2

**Additional context**
A few days back I faiced issues where the entire Aircon lost WiFi connection and only a complete Aircon disconnect beought everything back to life. After removing thr integration and setting it up again from scratch, the Aircon Wifi seems stable but the noe the integration looses connection.

**Comment by dprauser** [comment]
Additional errors include:
Logger: homeassistant.helpers.entity
Source: __main__.py:356
First occurred: 0:48:27 (7 occurrences)
Last logged: 7:56:26
Update of climate.midea_20890720942101 is taking over 10 seconds
