### ISSUE TITLE
ValueError: (7610, 'your account login too many times in one hour,please login later')

### ISSUE THREAD

**Issue by nathbullen** [andersonshatch/midea-ac-py#34]
Every few hours, control for my Midea aircon goes offline and trying to use the controls throws this error:
`ValueError: (7610, 'your account login too many times in one hour,please login later')`
It's only started happening recently, unsure as to what caused it but now the integration seems generally more unstable than it was previously.

 - Home Assistant version: 0.113.3
 - Midea integration version (commit hash): commit 661ba8844a548401ebb30b61ed9654e059bd6ea7

**Comment by andersonshatch** [comment]
I suspect the 60 second poll time is too much for their APIs -- they just had a fairly long outage yesterday.

Can you try to add the following lines to your `custom_components/midea/climate.py` file:
```
from datetime import timedelta
SCAN_INTERVAL = timedelta(minutes=5)
```

It's a little difficult for me to test this because my device gets set to fan only mode whenever the update request happens, so I have disabled polling.

**Comment by nathbullen** [comment]
Thanks for the quick response mate, I've just added those lines to the file, I'll let you know how it goes!

**Comment by nathbullen** [comment]
hey @andersonshatch - no dice unfortunately, it still throws the same error seemingly at random. I've pasted in the full error from the logs (sorry, that probably would have been more helpful first time around)

```
Source: custom_components/midea/climate.py:122
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 272, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 463, in async_device_update
    await self.async_update()  # type: ignore
  File "/config/custom_components/midea/climate.py", line 122, in async_update
    await self.hass.async_add_executor_job(self._device.refresh)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/midea/device.py", line 146, in refresh
    data = self._cloud_service.appliance_transparent_send(self.id, data)
  File "/usr/local/lib/python3.8/site-packages/midea/cloud.py", line 171, in appliance_transparent_send
    response = self.api_request('appliance/transparent/send', {
  File "/usr/local/lib/python3.8/site-packages/midea/cloud.py", line 89, in api_request
    self.handle_api_error(int(response['errorCode']), response['msg'])
  File "/usr/local/lib/python3.8/site-packages/midea/cloud.py", line 225, in handle_api_error
    handler()
  File "/usr/local/lib/python3.8/site-packages/midea/cloud.py", line 207, in session_restart
    self.login()
  File "/usr/local/lib/python3.8/site-packages/midea/cloud.py", line 121, in login
    self.session = self.api_request("user/login", {
  File "/usr/local/lib/python3.8/site-packages/midea/cloud.py", line 89, in api_request
    self.handle_api_error(int(response['errorCode']), response['msg'])
  File "/usr/local/lib/python3.8/site-packages/midea/cloud.py", line 225, in handle_api_error
    handler()
  File "/usr/local/lib/python3.8/site-packages/midea/cloud.py", line 201, in restart_full
    self.login()
  File "/usr/local/lib/python3.8/site-packages/midea/cloud.py", line 121, in login
    self.session = self.api_request("user/login", {
  File "/usr/local/lib/python3.8/site-packages/midea/cloud.py", line 89, in api_request
    self.handle_api_error(int(response['errorCode']), response['msg'])
  File "/usr/local/lib/python3.8/site-packages/midea/cloud.py", line 225, in handle_api_error
    handler()
  File "/usr/local/lib/python3.8/site-packages/midea/cloud.py", line 201, in restart_full
    self.login()
  File "/usr/local/lib/python3.8/site-packages/midea/cloud.py", line 121, in login
    self.session = self.api_request("user/login", {
  File "/usr/local/lib/python3.8/site-packages/midea/cloud.py", line 89, in api_request
    self.handle_api_error(int(response['errorCode']), response['msg'])
  File "/usr/local/lib/python3.8/site-packages/midea/cloud.py", line 225, in handle_api_error
    handler()
  File "/usr/local/lib/python3.8/site-packages/midea/cloud.py", line 210, in throw
    raise ValueError(error_code, message)
ValueError: (7610, 'your account login too many times in one hour,please login later')
```

and then under a separate entry in the log:

```
Integration: Home Assistant WebSocket API
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 125, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1281, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1316, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 595, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/config/custom_components/midea/climate.py", line 258, in async_set_swing_mode
    await self.apply_changes()
  File "/config/custom_components/midea/climate.py", line 109, in apply_changes
    await self.hass.async_add_executor_job(self._device.apply)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/midea/device.py", line 168, in apply
    data = self._cloud_service.appliance_transparent_send(self.id, data)
  File "/usr/local/lib/python3.8/site-packages/midea/cloud.py", line 166, in appliance_transparent_send
    self.login()
  File "/usr/local/lib/python3.8/site-packages/midea/cloud.py", line 121, in login
    self.session = self.api_request("user/login", {
  File "/usr/local/lib/python3.8/site-packages/midea/cloud.py", line 89, in api_request
    self.handle_api_error(int(response['errorCode']), response['msg'])
  File "/usr/local/lib/python3.8/site-packages/midea/cloud.py", line 225, in handle_api_error
    handler()
  File "/usr/local/lib/python3.8/site-packages/midea/cloud.py", line 210, in throw
    raise ValueError(error_code, message)
ValueError: (7610, 'your account login too many times in one hour,please login later')
```

**Comment by tupe12334** [comment]
me too have this problem it show after few hours that its work fine

**Comment by dcupaiolo** [comment]
Hey @nathbullen Have you been successful in setting the interval to 10 minutes?

**Comment by nathbullen** [comment]
hey @dcupaiolo unfortunately not, I've tried 15 minutes too with no luck. Just changed to 30 minutes, hopefully that helps. Anyone else had any luck?

**Comment by fraschizzato** [comment]
Same here, I would try to change app_key, but can't find it in Midea Air or Nethome Plus App. And can't find how to get one.

**Comment by Francois1976** [comment]
Hi all, I also experiment that problem.
