### ISSUE TITLE
Missing ON/OFF and Mode Buttons

### ISSUE THREAD

**Issue by angelpriet** [andersonshatch/midea-ac-py#9]
Hello,
I tried to install this fork in Hassio and it works!!! 
But... I can't make a "normal" usage of this... 
I mean, I can't power ON and OFF the aircon or set a mode (Auto, cool, dry...).
I'm still a newbie with HA but I would like to continue learning with this.
I attach a screenshot of the thermostat card on lovelace.
<img width="377" alt="Captura de pantalla 2019-08-04 a las 22 58 10" src="https://user-images.githubusercontent.com/45632303/62429226-2c2abe00-b70c-11e9-9b03-d1f09e391841.png">

**Comment by andersonshatch** [comment]
Which version of home assistant are you using?
Any errors mentioning Midea in the home assistant logfile?

**Comment by angelpriet** [comment]
> Which version of home assistant are you using? Any errors mentioning Midea in the home assistant logfile?
> […](#)

Home Assistant
0.94.3

And this is the log:

Mon Aug 05 2019 16:24:10 GMT+0200 (CEST)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 121, in handle_call_service
    connection.context(msg))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1150, in async_call
    self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1172, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 194, in handle_service
    required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 316, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 337, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/config/custom_components/midea/climate.py", line 282, in async_turn_on
    await self.apply_changes()
  File "/config/custom_components/midea/climate.py", line 92, in apply_changes
    await self.hass.async_add_executor_job(self._device.apply)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/midea/device.py", line 168, in apply
    data = self._cloud_service.appliance_transparent_send(self.id, data)
  File "/usr/local/lib/python3.7/site-packages/midea/cloud.py", line 173, in appliance_transparent_send
    'applianceId': id
  File "/usr/local/lib/python3.7/site-packages/midea/cloud.py", line 93, in api_request
    return self.api_request(endpoint, args)
  File "/usr/local/lib/python3.7/site-packages/midea/cloud.py", line 95, in api_request
    raise RecursionError()
RecursionError

**Comment by andersonshatch** [comment]
Aha! The minimum version of home-assistant for this component is 0.96.0
It should work when you upgrade hass :)
